env:
  browser: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  requireConfigFile: false
  ecmaFeatures:
    jsx: true
  sourceType: module
  babelOptions:
    presets:
      - '@babel/preset-react'
parser: '@babel/eslint-parser'
plugins:
  - react
rules:
  react/jsx-filename-extension: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
